// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// catchment_areas
arma::mat catchment_areas(arma::mat origins, arma::mat destinations, arma::vec supply, arma::vec demand, arma::vec fips);
RcppExport SEXP _safc_catchment_areas(SEXP originsSEXP, SEXP destinationsSEXP, SEXP supplySEXP, SEXP demandSEXP, SEXP fipsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type origins(originsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type destinations(destinationsSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type supply(supplySEXP);
    Rcpp::traits::input_parameter< arma::vec >::type demand(demandSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type fips(fipsSEXP);
    rcpp_result_gen = Rcpp::wrap(catchment_areas(origins, destinations, supply, demand, fips));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_safc_catchment_areas", (DL_FUNC) &_safc_catchment_areas, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_safc(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
