# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rmultinom <- function(n_boot, num, length, weight) {
    .Call('_safc_rmultinom', PACKAGE = 'safc', n_boot, num, length, weight)
}

get_demboot <- function(agg_index, num, weight, n_boot, n_dest, n_region) {
    .Call('_safc_get_demboot', PACKAGE = 'safc', agg_index, num, weight, n_boot, n_dest, n_region)
}

dist <- function(origin, destinations) {
    .Call('_safc_dist', PACKAGE = 'safc', origin, destinations)
}

get_distmat <- function(origins, destinations, max_dist, n_origin) {
    .Call('_safc_get_distmat', PACKAGE = 'safc', origins, destinations, max_dist, n_origin)
}

calc_avail <- function(supply, demand, distmat, agg_index, n_region, n_origin) {
    .Call('_safc_calc_avail', PACKAGE = 'safc', supply, demand, distmat, agg_index, n_region, n_origin)
}

get_availability <- function(supply, demand, distmat, agg_index, n_region, n_origin) {
    .Call('_safc_get_availability', PACKAGE = 'safc', supply, demand, distmat, agg_index, n_region, n_origin)
}

progress <- function(s, n_iter) {
    invisible(.Call('_safc_progress', PACKAGE = 'safc', s, n_iter))
}

