# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.catchment_areas <- function(origins, destinations, supply, demand, fips) {
    .Call('_safc_catchment_areas', PACKAGE = 'safc', origins, destinations, supply, demand, fips)
}

